services:
  backend-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=GZVcnLBTsrdsTXga
      - POSTGRES_USER=backend
      - POSTGRES_DB=backend
    hostname: backenddatabase
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  backend:
    image: wetcries/architecture-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/backend/config:/usr/src/myapp/config
    depends_on:
      - "backend-database"
      - "mlserver"

  mlserver:
    image: kolyapak98/server_ml
    hostname: mlserver