server:
  port: 8080
  servlet:
    context-path: /backend

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

ml-server-url: http://localhost:5050

jwt:
  secretKey: asdfaskldfjwklejfwlkjfwjfeklsadf
  tokenExpirationAfterDays: 10